[workspace]
members = ["crates/*"]

[package]
name = "mythic"
version = "0.2.0"
edition = "2021"
description = "Mythic is a native blockchain navigator."
authors = ["Primitive Bits, Inc."]
license = "MIT OR Apache-2.0"
repository = "https://github.com/primitivefinance/mythic"
readme = "README.md"

[[bin]]
name = "mythic"
path = "src/main.rs"

[workspace.dependencies]

mythic_charts = { path = "crates/mythic_charts", version = "0.2.0" }

ethers = { version = "=2.0.13", features = ["ws", "openssl", "rustls"] }

# Networking
reqwest = "0.11.24"

## Config and parsing
serde = "=1.0.203"
serde_json = "=1.0.114"
serde_with = { version = "3.6.1", features = ["chrono_0_4"] }
config = "0.14.0"

## Async
tokio = { version = "=1.36.0", features = ["macros", "full"] }
async-trait = "=0.1.77"

## Error and logs
tracing = "=0.1.40"
tracing-subscriber = { version = "=0.3.18", features = ["env-filter"] }
tracing-futures = { version = "=0.2.5", default-features = false }
anyhow = "=1.0.80"
thiserror = "=1.0.61"

itertools = "0.12.1"
rand = "=0.8.5"
bytesize = "1.3.0"
dotenv = "=0.15.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
clap = { version = "4.5.0", features = ["derive"] }

# Visualization
plotters = "=0.3.5"

# math
RustQuant = { version = "0.0.49", features = ["seedable"] }
statrs = "=0.16.0"
reikna = "=0.12.3"

# Storage
linked-hash-map = "=0.5.6"
directories-next = "=2.0.0"

# Time
chrono = { version = "0.4.34", features = ["serde"] }

[dependencies]
mythic_charts.workspace = true

ethers.workspace = true

serde.workspace = true
serde_json.workspace = true

reqwest.workspace = true
chrono.workspace = true

tokio.workspace = true
async-trait.workspace = true

reikna.workspace = true
plotters.workspace = true

clap.workspace = true


# Env and logs
directories-next.workspace = true
dotenv.workspace = true
uuid.workspace = true
tracing.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true

# Math
RustQuant.workspace = true
statrs.workspace = true

iced = { version = "=0.13.1", default-features = true, features = [
    "system",
    "tokio",
    "lazy",
    "image",
    "advanced",
    "canvas",
    "svg",
] }
iced_core = { version = "=0.13.1" }
iced_aw = { version = "=0.10.0", default-features = true }
plotters-backend = "=0.3.5"
plotters-iced = "=0.11.0"
url = "=2.5.0"
alloy = { version = "0.3.6", features = ["full"] }
futures-util = "0.3.30"

[package.metadata.bundle]
name = "Mythic"
identifier = "xyz.primitive.mythic"
short_description = "Mythic is a native blockchain navigator."
long_description = "Mythic is a native blockchain navigator."
resources = ["assets/"]
icon = ["assets/logos/excalibur_logo_2.png"]

# macOS specific
category = "public.app-category.utilities"
copyright = "Copyright (c) 2024 Primitive Bits, Inc."
minimum_system_version = "10.14"
osx_url_schemes = ["xyz.primitive.mythic"]

# Windows specific
product_name = "Mythic"
manufacturer = "Primitive Bits, Inc."

# Linux specific
package_name = "mythic"
package_version = "0.1.0"
