#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod arbiter_token;
pub mod atomic_v2;
pub mod bisection_lib;
pub mod coin;
pub mod counter;
pub mod dfmm;
pub mod erc20;
pub mod fixed_point_math_lib;
pub mod g3m;
pub mod g3m_extended_lib;
pub mod g3m_lib;
pub mod g_3m_solver;
pub mod gaussian;
pub mod i_core;
pub mod i_strategy;
pub mod ierc721_token_receiver;
pub mod lex;
pub mod liquid_exchange;
pub mod log_normal;
pub mod log_normal_extended_lib;
pub mod log_normal_lib;
pub mod log_normal_math;
pub mod log_normal_solver;
pub mod mock_erc20;
pub mod mock_erc721;
pub mod mock_token_like;
pub mod profit_finder;
pub mod shared_types;
pub mod strategy_lib;
pub mod strategy_like;
pub mod strategy_source;
pub mod token_like;
pub mod units;
